import execa from "execa"
import { NetlifyCLIPath, NetlifyCLIPath_createDevTime } from "./NetlifyCLIPath"

export class NetlifyCLIWrapper {
  constructor(private clipath: NetlifyCLIPath) {}
  async functions_create_list_templates() {
    const res = await execa(this.clipath.x, [
      "functions:create",
      "--ide_templates",
    ])
    return JSON.parse(res.stdout) as FuncTemplateData[]
  }
  async info(cwd: string) {
    const res = await execa(this.clipath.x, ["ide"], { cwd })
    return JSON.parse(res.stdout)
  }
}

export interface FuncTemplateData {
  name: string
  priority: number
  description: string
  lang: string
}

{
  const pp = NetlifyCLIPath_createDevTime()
  const cliw = new NetlifyCLIWrapper(pp)
  // cliw.functions_create_list_templates()
  const info = await cliw.info(
    "/Users/aldo/com.github/decoupled/netlify-test-site"
  )
  console.log(info)
}

const out = {
  normalizedFunctions: [
    {
      name: "fooooof",
      url: "/.netlify/functions/fooooof",
      isDeployed: false,
    },
    {
      name: "my-apollo",
      url: "/.netlify/functions/my-apollo",
      isDeployed: false,
    },
  ],
  netlify: {
    api: {
      defaultHeaders: {
        "User-agent": "netlify/js-client",
        accept: "application/json",
        Authorization: "_________",
      },
      scheme: "https",
      host: "api.netlify.com",
      pathPrefix: "/api/v1",
      globalParams: {},
    },
    site: {
      root: "/Users/aldo/com.github/decoupled/netlify-test-site",
      configPath:
        "/Users/aldo/com.github/decoupled/netlify-test-site/netlify.toml",
      id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
    },
    siteInfo: {
      id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
      site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
      plan: "nf_team_dev",
      ssl_plan: null,
      premium: false,
      claimed: true,
      name: "xenodochial-torvalds-5752f5",
      custom_domain: null,
      domain_aliases: [],
      password: null,
      notification_email: null,
      url: "http://xenodochial-torvalds-5752f5.netlify.app",
      admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
      deploy_id: "5f35b1befa10e1009b644d8e",
      build_id: "",
      deploy_url:
        "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
      state: "current",
      screenshot_url:
        "https://d33wubrfki0l68.cloudfront.net/5f35b1befa10e1009b644d8e/screenshot.png",
      created_at: "2020-08-13T21:33:50.944Z",
      updated_at: "2021-05-05T21:44:04.256Z",
      user_id: "5ca4dcd877614601753fdded",
      error_message: null,
      ssl: false,
      ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
      force_ssl: null,
      ssl_status: null,
      max_domain_aliases: 100,
      build_settings: {
        cmd: "gatsby build",
        dir: "public/",
        env: {
          myvarname: "myvarvalue",
        },
        created_at: "2020-08-13T21:33:50.966Z",
        updated_at: "2021-05-05T21:44:04.252Z",
        private_logs: null,
        allowed_branches: [],
        functions_dir: "netlify/functions",
        installation_id: 11237437,
        skip_prs: null,
        untrusted_flow: "review",
        base_rel_dir: true,
        stop_builds: false,
        public_repo: false,
        skip_automatic_builds: null,
        provider: "github",
        repo_type: "git",
        repo_url: "https://github.com/decoupled/netlify-test-site",
        repo_branch: "master",
        repo_path: "decoupled/netlify-test-site",
        base: null,
        deploy_key_id: null,
      },
      processing_settings: {
        css: {
          bundle: true,
          minify: true,
        },
        js: {
          bundle: true,
          minify: true,
        },
        images: {
          optimize: true,
        },
        html: {
          pretty_urls: true,
        },
        skip: true,
        ignore_html_forms: false,
      },
      prerender: null,
      prerender_headers: null,
      deploy_hook: "https://api.netlify.com/hooks/github",
      published_deploy: {
        id: "5f35b1befa10e1009b644d8e",
        site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
        build_id: "5f35b1befa10e1009b644d8c",
        state: "ready",
        name: "xenodochial-torvalds-5752f5",
        url: "http://xenodochial-torvalds-5752f5.netlify.app",
        ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
        admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
        deploy_url:
          "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
        deploy_ssl_url:
          "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
        created_at: "2020-08-13T21:33:50.988Z",
        updated_at: "2021-05-05T21:44:04.266Z",
        user_id: "5ca4dcd877614601753fdded",
        error_message: null,
        required: [],
        required_functions: [],
        commit_ref: null,
        review_id: null,
        branch: "master",
        commit_url: null,
        skipped: null,
        locked: null,
        log_access_attributes: {
          type: "firebase",
          url:
            "https://netlify-builds3.firebaseio.com/builds/5f35b1befa10e1009b644d8c/log",
          endpoint: "https://netlify-builds3.firebaseio.com",
          path: "/builds/5f35b1befa10e1009b644d8c/log",
          token:
            "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJpYXQiOjE2MjI2ODYwNzIsImQiOnsidWlkIjoiIn19.tiirEf4HcL2POpay2R_dPmFVaA_fWvBu_GGdHGZ2jjw",
        },
        title: null,
        review_url: null,
        published_at: "2020-08-13T21:35:18.869Z",
        context: "production",
        deploy_time: 66,
        available_functions: [],
        screenshot_url:
          "https://d33wubrfki0l68.cloudfront.net/5f35b1befa10e1009b644d8e/screenshot.png",
        site_capabilities: {
          title: "Netlify Team Free",
          asset_acceleration: true,
          form_processing: true,
          cdn_propagation: "partial",
          build_node_pool: "buildbot-external-ssd",
          domain_aliases: true,
          secure_site: false,
          prerendering: true,
          proxying: true,
          ssl: "custom",
          rate_cents: 0,
          yearly_rate_cents: 0,
          ipv6_domain: "cdn.makerloop.com",
          branch_deploy: true,
          managed_dns: true,
          geo_ip: true,
          split_testing: true,
          id: "nf_team_dev",
          cdn_tier: "reg",
        },
        committer: null,
        skipped_log: null,
        manual_deploy: false,
        file_tracking_optimization: true,
        plugin_state: "none",
        has_edge_handlers: false,
        links: {
          permalink:
            "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
          alias: "https://xenodochial-torvalds-5752f5.netlify.app",
          branch: null,
        },
        framework: null,
        entry_path: null,
      },
      managed_dns: true,
      jwt_secret: null,
      jwt_roles_path: "app_metadata.authorization.roles",
      account_slug: "aldonline",
      account_name: "Aldo Bucchi's team",
      account_type: "Starter",
      capabilities: {
        title: "Netlify Team Free",
        asset_acceleration: true,
        form_processing: true,
        cdn_propagation: "partial",
        build_node_pool: "buildbot-external-ssd",
        domain_aliases: true,
        secure_site: false,
        prerendering: true,
        proxying: true,
        ssl: "custom",
        rate_cents: 0,
        yearly_rate_cents: 0,
        ipv6_domain: "cdn.makerloop.com",
        branch_deploy: true,
        managed_dns: true,
        geo_ip: true,
        split_testing: true,
        id: "nf_team_dev",
        cdn_tier: "reg",
      },
      dns_zone_id: null,
      identity_instance_id: null,
      use_functions: null,
      use_edge_handlers: null,
      parent_user_id: null,
      automatic_tls_provisioning: null,
      disabled: null,
      lifecycle_state: "active",
      id_domain: "f0acc552-da82-4a61-a0d4-2843fcd94695.netlify.app",
      use_lm: null,
      build_image: "xenial",
      automatic_tls_provisioning_expired: false,
      analytics_instance_id: null,
      functions_region: null,
      functions_config: {
        site_created_at: "2020-08-13T21:33:50.944Z",
      },
      plugins: [],
      account_subdomain: null,
      functions_env: {},
      default_domain: "xenodochial-torvalds-5752f5.netlify.app",
    },
    config: {
      functionsDirectory:
        "/Users/aldo/com.github/decoupled/netlify-test-site/netlify/functions",
      functionsDirectoryOrigin: "ui",
      dev: {
        targetPort: 4000,
      },
      functions: {},
      plugins: [],
      build: {
        environment: {},
        publish: "/Users/aldo/com.github/decoupled/netlify-test-site/public",
        command: "gatsby build",
        commandOrigin: "ui",
        functions:
          "/Users/aldo/com.github/decoupled/netlify-test-site/netlify/functions",
      },
    },
    cachedConfig: {
      siteInfo: {
        id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
        site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
        plan: "nf_team_dev",
        ssl_plan: null,
        premium: false,
        claimed: true,
        name: "xenodochial-torvalds-5752f5",
        custom_domain: null,
        domain_aliases: [],
        password: null,
        notification_email: null,
        url: "http://xenodochial-torvalds-5752f5.netlify.app",
        admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
        deploy_id: "5f35b1befa10e1009b644d8e",
        build_id: "",
        deploy_url:
          "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
        state: "current",
        screenshot_url:
          "https://d33wubrfki0l68.cloudfront.net/5f35b1befa10e1009b644d8e/screenshot.png",
        created_at: "2020-08-13T21:33:50.944Z",
        updated_at: "2021-05-05T21:44:04.256Z",
        user_id: "5ca4dcd877614601753fdded",
        error_message: null,
        ssl: false,
        ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
        force_ssl: null,
        ssl_status: null,
        max_domain_aliases: 100,
        build_settings: {
          cmd: "gatsby build",
          dir: "public/",
          env: {
            myvarname: "myvarvalue",
          },
          created_at: "2020-08-13T21:33:50.966Z",
          updated_at: "2021-05-05T21:44:04.252Z",
          private_logs: null,
          allowed_branches: [],
          functions_dir: "netlify/functions",
          installation_id: 11237437,
          skip_prs: null,
          untrusted_flow: "review",
          base_rel_dir: true,
          stop_builds: false,
          public_repo: false,
          skip_automatic_builds: null,
          provider: "github",
          repo_type: "git",
          repo_url: "https://github.com/decoupled/netlify-test-site",
          repo_branch: "master",
          repo_path: "decoupled/netlify-test-site",
          base: null,
          deploy_key_id: null,
        },
        processing_settings: {
          css: {
            bundle: true,
            minify: true,
          },
          js: {
            bundle: true,
            minify: true,
          },
          images: {
            optimize: true,
          },
          html: {
            pretty_urls: true,
          },
          skip: true,
          ignore_html_forms: false,
        },
        prerender: null,
        prerender_headers: null,
        deploy_hook: "https://api.netlify.com/hooks/github",
        published_deploy: {
          id: "5f35b1befa10e1009b644d8e",
          site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
          build_id: "5f35b1befa10e1009b644d8c",
          state: "ready",
          name: "xenodochial-torvalds-5752f5",
          url: "http://xenodochial-torvalds-5752f5.netlify.app",
          ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
          admin_url:
            "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
          deploy_url:
            "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
          deploy_ssl_url:
            "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
          created_at: "2020-08-13T21:33:50.988Z",
          updated_at: "2021-05-05T21:44:04.266Z",
          user_id: "5ca4dcd877614601753fdded",
          error_message: null,
          required: [],
          required_functions: [],
          commit_ref: null,
          review_id: null,
          branch: "master",
          commit_url: null,
          skipped: null,
          locked: null,
          log_access_attributes: {
            type: "firebase",
            url:
              "https://netlify-builds3.firebaseio.com/builds/5f35b1befa10e1009b644d8c/log",
            endpoint: "https://netlify-builds3.firebaseio.com",
            path: "/builds/5f35b1befa10e1009b644d8c/log",
            token:
              "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJpYXQiOjE2MjI2ODYwNzIsImQiOnsidWlkIjoiIn19.tiirEf4HcL2POpay2R_dPmFVaA_fWvBu_GGdHGZ2jjw",
          },
          title: null,
          review_url: null,
          published_at: "2020-08-13T21:35:18.869Z",
          context: "production",
          deploy_time: 66,
          available_functions: [],
          screenshot_url:
            "https://d33wubrfki0l68.cloudfront.net/5f35b1befa10e1009b644d8e/screenshot.png",
          site_capabilities: {
            title: "Netlify Team Free",
            asset_acceleration: true,
            form_processing: true,
            cdn_propagation: "partial",
            build_node_pool: "buildbot-external-ssd",
            domain_aliases: true,
            secure_site: false,
            prerendering: true,
            proxying: true,
            ssl: "custom",
            rate_cents: 0,
            yearly_rate_cents: 0,
            ipv6_domain: "cdn.makerloop.com",
            branch_deploy: true,
            managed_dns: true,
            geo_ip: true,
            split_testing: true,
            id: "nf_team_dev",
            cdn_tier: "reg",
          },
          committer: null,
          skipped_log: null,
          manual_deploy: false,
          file_tracking_optimization: true,
          plugin_state: "none",
          has_edge_handlers: false,
          links: {
            permalink:
              "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
            alias: "https://xenodochial-torvalds-5752f5.netlify.app",
            branch: null,
          },
          framework: null,
          entry_path: null,
        },
        managed_dns: true,
        jwt_secret: null,
        jwt_roles_path: "app_metadata.authorization.roles",
        account_slug: "aldonline",
        account_name: "Aldo Bucchi's team",
        account_type: "Starter",
        capabilities: {
          title: "Netlify Team Free",
          asset_acceleration: true,
          form_processing: true,
          cdn_propagation: "partial",
          build_node_pool: "buildbot-external-ssd",
          domain_aliases: true,
          secure_site: false,
          prerendering: true,
          proxying: true,
          ssl: "custom",
          rate_cents: 0,
          yearly_rate_cents: 0,
          ipv6_domain: "cdn.makerloop.com",
          branch_deploy: true,
          managed_dns: true,
          geo_ip: true,
          split_testing: true,
          id: "nf_team_dev",
          cdn_tier: "reg",
        },
        dns_zone_id: null,
        identity_instance_id: null,
        use_functions: null,
        use_edge_handlers: null,
        parent_user_id: null,
        automatic_tls_provisioning: null,
        disabled: null,
        lifecycle_state: "active",
        id_domain: "f0acc552-da82-4a61-a0d4-2843fcd94695.netlify.app",
        use_lm: null,
        build_image: "xenial",
        automatic_tls_provisioning_expired: false,
        analytics_instance_id: null,
        functions_region: null,
        functions_config: {
          site_created_at: "2020-08-13T21:33:50.944Z",
        },
        plugins: [],
        account_subdomain: null,
        functions_env: {},
        default_domain: "xenodochial-torvalds-5752f5.netlify.app",
      },
      env: {
        myvarname: {
          sources: ["ui"],
          value: "myvarvalue",
        },
        SITE_ID: {
          sources: ["general"],
          value: "f0acc552-da82-4a61-a0d4-2843fcd94695",
        },
        SITE_NAME: {
          sources: ["general"],
          value: "xenodochial-torvalds-5752f5",
        },
        URL: {
          sources: ["general"],
          value: "http://xenodochial-torvalds-5752f5.netlify.app",
        },
        REPOSITORY_URL: {
          sources: ["general"],
          value: "https://github.com/decoupled/netlify-test-site",
        },
        CONTEXT: {
          sources: ["general"],
          value: "production",
        },
        BRANCH: {
          sources: ["general"],
          value: "master",
        },
        HEAD: {
          sources: ["general"],
          value: "master",
        },
        COMMIT_REF: {
          sources: ["general"],
          value: "01f12ec5d090960c48daed4895ecae08cb507081",
        },
        PULL_REQUEST: {
          sources: ["general"],
          value: "false",
        },
        LANG: {
          sources: ["general"],
          value: "en_US.UTF-8",
        },
        LANGUAGE: {
          sources: ["general"],
          value: "en_US:en",
        },
        LC_ALL: {
          sources: ["general"],
          value: "en_US.UTF-8",
        },
        GATSBY_TELEMETRY_DISABLED: {
          sources: ["general"],
          value: "1",
        },
        NEXT_TELEMETRY_DISABLED: {
          sources: ["general"],
          value: "1",
        },
      },
      configPath:
        "/Users/aldo/com.github/decoupled/netlify-test-site/netlify.toml",
      buildDir: "/Users/aldo/com.github/decoupled/netlify-test-site",
      config: {
        functionsDirectory:
          "/Users/aldo/com.github/decoupled/netlify-test-site/netlify/functions",
        functionsDirectoryOrigin: "ui",
        dev: {
          targetPort: 4000,
        },
        functions: {},
        plugins: [],
        build: {
          environment: {},
          publish: "/Users/aldo/com.github/decoupled/netlify-test-site/public",
          command: "gatsby build",
          commandOrigin: "ui",
          functions:
            "/Users/aldo/com.github/decoupled/netlify-test-site/netlify/functions",
        },
      },
      context: "production",
      branch: "master",
      token: "18b2a72dcc3402758f6f0ab2e70629965dcf6e9edc87793be90c8a18a993f426",
      api: {
        defaultHeaders: {
          "User-agent": "netlify/js-client",
          accept: "application/json",
          Authorization:
            "Bearer 18b2a72dcc3402758f6f0ab2e70629965dcf6e9edc87793be90c8a18a993f426",
        },
        scheme: "https",
        host: "api.netlify.com",
        pathPrefix: "/api/v1",
        globalParams: {},
      },
    },
    globalConfig: {
      path: "/Users/aldo/Library/Preferences/netlify/config.json",
    },
    state: {
      path:
        "/Users/aldo/com.github/decoupled/netlify-test-site/.netlify/state.json",
    },
  },
  siteData: {
    id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
    site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
    plan: "nf_team_dev",
    ssl_plan: null,
    premium: false,
    claimed: true,
    name: "xenodochial-torvalds-5752f5",
    custom_domain: null,
    domain_aliases: [],
    password: null,
    notification_email: null,
    url: "http://xenodochial-torvalds-5752f5.netlify.app",
    admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
    deploy_id: "5f35b1befa10e1009b644d8e",
    build_id: "",
    deploy_url:
      "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
    state: "current",
    screenshot_url:
      "https://d33wubrfki0l68.cloudfront.net/5f35b1befa10e1009b644d8e/screenshot.png",
    created_at: "2020-08-13T21:33:50.944Z",
    updated_at: "2021-05-05T21:44:04.256Z",
    user_id: "5ca4dcd877614601753fdded",
    error_message: null,
    ssl: false,
    ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
    force_ssl: null,
    ssl_status: null,
    max_domain_aliases: 100,
    build_settings: {
      cmd: "gatsby build",
      dir: "public/",
      env: {
        myvarname: "myvarvalue",
      },
      created_at: "2020-08-13T21:33:50.966Z",
      updated_at: "2021-05-05T21:44:04.252Z",
      private_logs: null,
      allowed_branches: [],
      functions_dir: "netlify/functions",
      installation_id: 11237437,
      skip_prs: null,
      untrusted_flow: "review",
      base_rel_dir: true,
      stop_builds: false,
      public_repo: false,
      skip_automatic_builds: null,
      provider: "github",
      repo_type: "git",
      repo_url: "https://github.com/decoupled/netlify-test-site",
      repo_branch: "master",
      repo_path: "decoupled/netlify-test-site",
      base: null,
      deploy_key_id: null,
    },
    processing_settings: {
      css: {
        bundle: true,
        minify: true,
      },
      js: {
        bundle: true,
        minify: true,
      },
      images: {
        optimize: true,
      },
      html: {
        pretty_urls: true,
      },
      skip: true,
      ignore_html_forms: false,
    },
    prerender: null,
    prerender_headers: null,
    deploy_hook: "https://api.netlify.com/hooks/github",
    published_deploy: {
      id: "5f35b1befa10e1009b644d8e",
      site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
      build_id: "5f35b1befa10e1009b644d8c",
      state: "ready",
      name: "xenodochial-torvalds-5752f5",
      url: "http://xenodochial-torvalds-5752f5.netlify.app",
      ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
      admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
      deploy_url:
        "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
      deploy_ssl_url:
        "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
      created_at: "2020-08-13T21:33:50.988Z",
      updated_at: "2021-05-05T21:44:04.266Z",
      user_id: "5ca4dcd877614601753fdded",
      error_message: null,
      required: [],
      required_functions: [],
      commit_ref: null,
      review_id: null,
      branch: "master",
      commit_url: null,
      skipped: null,
      locked: null,
      log_access_attributes: {
        type: "firebase",
        url:
          "https://netlify-builds3.firebaseio.com/builds/5f35b1befa10e1009b644d8c/log",
        endpoint: "https://netlify-builds3.firebaseio.com",
        path: "/builds/5f35b1befa10e1009b644d8c/log",
        token:
          "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJpYXQiOjE2MjI2ODYwNzIsImQiOnsidWlkIjoiIn19.tiirEf4HcL2POpay2R_dPmFVaA_fWvBu_GGdHGZ2jjw",
      },
      title: null,
      review_url: null,
      published_at: "2020-08-13T21:35:18.869Z",
      context: "production",
      deploy_time: 66,
      available_functions: [],
      screenshot_url:
        "https://d33wubrfki0l68.cloudfront.net/5f35b1befa10e1009b644d8e/screenshot.png",
      site_capabilities: {
        title: "Netlify Team Free",
        asset_acceleration: true,
        form_processing: true,
        cdn_propagation: "partial",
        build_node_pool: "buildbot-external-ssd",
        domain_aliases: true,
        secure_site: false,
        prerendering: true,
        proxying: true,
        ssl: "custom",
        rate_cents: 0,
        yearly_rate_cents: 0,
        ipv6_domain: "cdn.makerloop.com",
        branch_deploy: true,
        managed_dns: true,
        geo_ip: true,
        split_testing: true,
        id: "nf_team_dev",
        cdn_tier: "reg",
      },
      committer: null,
      skipped_log: null,
      manual_deploy: false,
      file_tracking_optimization: true,
      plugin_state: "none",
      has_edge_handlers: false,
      links: {
        permalink:
          "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
        alias: "https://xenodochial-torvalds-5752f5.netlify.app",
        branch: null,
      },
      framework: null,
      entry_path: null,
    },
    managed_dns: true,
    jwt_secret: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    account_slug: "aldonline",
    account_name: "Aldo Bucchi's team",
    account_type: "Starter",
    capabilities: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_node_pool: "buildbot-external-ssd",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev",
      cdn_tier: "reg",
    },
    dns_zone_id: null,
    identity_instance_id: null,
    use_functions: null,
    use_edge_handlers: null,
    parent_user_id: null,
    automatic_tls_provisioning: null,
    disabled: null,
    lifecycle_state: "active",
    id_domain: "f0acc552-da82-4a61-a0d4-2843fcd94695.netlify.app",
    use_lm: null,
    build_image: "xenial",
    automatic_tls_provisioning_expired: false,
    analytics_instance_id: null,
    functions_region: null,
    functions_config: {
      site_created_at: "2020-08-13T21:33:50.944Z",
    },
    plugins: [],
    account_subdomain: null,
    functions_env: {},
    default_domain: "xenodochial-torvalds-5752f5.netlify.app",
  },
}
