export type R_listSites = typeof listSites
export const listSites = [
  {
    id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
    site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
    plan: "nf_team_dev",
    ssl_plan: null,
    premium: false,
    claimed: true,
    name: "xenodochial-torvalds-5752f5",
    custom_domain: null,
    domain_aliases: [],
    password: null,
    notification_email: null,
    url: "http://xenodochial-torvalds-5752f5.netlify.app",
    admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
    deploy_id: "5f35b1befa10e1009b644d8e",
    build_id: "",
    deploy_url:
      "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
    state: "current",
    screenshot_url:
      "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5f35b1befa10e1009b644d8e/screenshot.png",
    created_at: "2020-08-13T21:33:50.944Z",
    updated_at: "2020-08-13T21:35:21.166Z",
    user_id: "5ca4dcd877614601753fdded",
    error_message: null,
    ssl: false,
    ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
    force_ssl: null,
    ssl_status: null,
    max_domain_aliases: 100,
    build_settings: {
      cmd: "gatsby build",
      dir: "public/",
      env: {},
      created_at: "2020-08-13T21:33:50.966Z",
      updated_at: "2020-08-13T21:33:50.966Z",
      private_logs: null,
      allowed_branches: ["master"],
      functions_dir: null,
      installation_id: 11237437,
      skip_prs: null,
      untrusted_flow: "review",
      base_rel_dir: true,
      stop_builds: false,
      public_repo: false,
      provider: "github",
      repo_type: "git",
      repo_url: "https://github.com/decoupled/netlify-test-site",
      repo_branch: "master",
      repo_path: "decoupled/netlify-test-site",
      base: null,
      deploy_key_id: null,
    },
    processing_settings: {
      css: { bundle: true, minify: true },
      js: { bundle: true, minify: true },
      images: { optimize: true },
      html: { pretty_urls: true },
      skip: true,
    },
    prerender: null,
    prerender_headers: null,
    deploy_hook: "https://api.netlify.com/hooks/github",
    published_deploy: {
      id: "5f35b1befa10e1009b644d8e",
      site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
      build_id: "5f35b1befa10e1009b644d8c",
      state: "ready",
      name: "xenodochial-torvalds-5752f5",
      url: "http://xenodochial-torvalds-5752f5.netlify.app",
      ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
      admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
      deploy_url:
        "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
      deploy_ssl_url:
        "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
      created_at: "2020-08-13T21:33:50.988Z",
      updated_at: "2020-08-13T21:35:21.151Z",
      user_id: "5ca4dcd877614601753fdded",
      error_message: null,
      required: [],
      required_functions: [],
      commit_ref: null,
      review_id: null,
      branch: "master",
      commit_url: null,
      skipped: null,
      locked: null,
      log_access_attributes: {
        type: "firebase",
        url:
          "https://netlify-builds3.firebaseio.com/builds/5f35b1befa10e1009b644d8c/log",
        endpoint: "https://netlify-builds3.firebaseio.com",
        path: "/builds/5f35b1befa10e1009b644d8c/log",
        token:
          "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJpYXQiOjE1OTczNTk1NzMsImQiOnsidWlkIjoiIn19.DBS5Gsh4mOud4HsM0x44MUCWP2SZnJNtqjbbtAL0480",
      },
      title: null,
      review_url: null,
      published_at: "2020-08-13T21:35:18.869Z",
      context: "production",
      deploy_time: 66,
      available_functions: [],
      summary: { status: "ready", messages: [Object] },
      screenshot_url:
        "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5f35b1befa10e1009b644d8e/screenshot.png",
      site_capabilities: {
        title: "Netlify Team Free",
        asset_acceleration: true,
        form_processing: true,
        cdn_propagation: "partial",
        build_gc_exchange: "buildbot-gc",
        build_node_pool: "buildbot-external-ssd",
        domain_aliases: true,
        secure_site: false,
        prerendering: true,
        proxying: true,
        ssl: "custom",
        rate_cents: 0,
        yearly_rate_cents: 0,
        ipv6_domain: "cdn.makerloop.com",
        branch_deploy: true,
        managed_dns: true,
        geo_ip: true,
        split_testing: true,
        id: "nf_team_dev",
        cdn_tier: "reg",
      },
      committer: null,
      skipped_log: null,
      manual_deploy: false,
      file_tracking_optimization: true,
      plugin_state: "none",
    },
    managed_dns: true,
    jwt_secret: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    account_slug: "aldonline",
    account_name: "Aldo Bucchi's team",
    account_type: "Starter",
    capabilities: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev",
      cdn_tier: "reg",
    },
    paid_individual_site_subscription: false,
    dns_zone_id: null,
    identity_instance_id: null,
    use_functions: null,
    parent_user_id: null,
    automatic_tls_provisioning: null,
    disabled: null,
    lifecycle_state: "active",
    id_domain: "f0acc552-da82-4a61-a0d4-2843fcd94695.netlify.app",
    use_lm: null,
    build_image: "xenial",
    automatic_tls_provisioning_expired: false,
    analytics_instance_id: null,
    functions_region: null,
    functions_config: { site_created_at: "2020-08-13T21:33:50.944Z" },
    plugins: [],
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {
      asset_acceleration: true,
      branch_deploy: true,
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      cdn_propagation: "partial",
      cdn_tier: "reg",
      domain_aliases: true,
      form_processing: true,
      geo_ip: true,
      id: "nf_team_dev",
      ipv6_domain: "cdn.makerloop.com",
      managed_dns: true,
      prerendering: true,
      proxying: true,
      rate_cents: 0,
      secure_site: false,
      split_testing: true,
      ssl: "custom",
      title: "Netlify Team Free",
      yearly_rate_cents: 0,
    },
    claimed: true,
    created_at: "2020-01-04T12:05:11.446Z",
    custom_domain: "dev.decoupled.com",
    deploy_hook: null,
    deploy_id: "5e55bfaa1036fdb7aa9759ab",
    deploy_url: "http://5e55bfaa1036fdb7aa9759ab--decoupled-dev.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: true,
    functions_config: { site_created_at: "2020-01-04T12:05:11.446Z" },
    functions_region: null,
    id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    id_domain: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "decoupled-dev",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: { css: {}, html: {}, images: {}, js: {}, skip: true },
    published_deploy: {
      admin_url: "https://app.netlify.com/sites/decoupled-dev",
      available_functions: [],
      branch: null,
      build_id: null,
      commit_ref: null,
      commit_url: null,
      committer: null,
      context: "production",
      created_at: "2020-02-26T00:45:30.387Z",
      deploy_ssl_url:
        "https://5e55bfaa1036fdb7aa9759ab--decoupled-dev.netlify.app",
      deploy_time: 5,
      deploy_url: "http://5e55bfaa1036fdb7aa9759ab--decoupled-dev.netlify.app",
      error_message: null,
      file_tracking_optimization: false,
      id: "5e55bfaa1036fdb7aa9759ab",
      locked: null,
      log_access_attributes: {},
      manual_deploy: true,
      name: "decoupled-dev",
      plugin_state: "none",
      published_at: "2020-02-26T00:45:36.205Z",
      required: [],
      required_functions: [],
      review_id: null,
      review_url: null,
      screenshot_url:
        "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5e55bfaa1036fdb7aa9759ab/screenshot.png",
      site_capabilities: {},
      site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
      skipped: null,
      skipped_log: null,
      ssl_url: "https://dev.decoupled.com",
      state: "ready",
      summary: {},
      title: null,
      updated_at: "2020-08-09T09:00:51.864Z",
      url: "https://dev.decoupled.com",
      user_id: "5ca4dcd877614601753fdded",
    },
    screenshot_url:
      "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5e55bfaa1036fdb7aa9759ab/screenshot.png",
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    ssl: true,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://dev.decoupled.com",
    state: "current",
    updated_at: "2020-08-09T09:00:53.441Z",
    url: "https://dev.decoupled.com",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/decoupled-studio-assets",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {},
    claimed: true,
    created_at: "2019-12-10T22:32:21.153Z",
    custom_domain: null,
    deploy_hook: null,
    deploy_id: "5f24e147b4b5b7789df8d3dd",
    deploy_url:
      "http://5f24e147b4b5b7789df8d3dd--decoupled-studio-assets.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: null,
    functions_config: {},
    functions_region: null,
    id: "051af138-64c6-4539-b9c0-0232013976f7",
    id_domain: "051af138-64c6-4539-b9c0-0232013976f7.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "decoupled-studio-assets",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: {},
    published_deploy: {},
    screenshot_url:
      "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5f24e147b4b5b7789df8d3dd/screenshot.png",
    site_id: "051af138-64c6-4539-b9c0-0232013976f7",
    ssl: false,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://decoupled-studio-assets.netlify.app",
    state: "current",
    updated_at: "2020-08-01T03:28:10.447Z",
    url: "http://decoupled-studio-assets.netlify.app",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/sad-sad-sad-site",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {},
    claimed: true,
    created_at: "2019-12-10T21:52:36.471Z",
    custom_domain: null,
    deploy_hook: null,
    deploy_id: "",
    deploy_url: "http://5f31efd0da650ecf809d284e--sad-sad-sad-site.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: null,
    functions_config: {},
    functions_region: null,
    id: "b330d6ff-1374-45fa-9dc9-2287a09ac461",
    id_domain: "b330d6ff-1374-45fa-9dc9-2287a09ac461.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "sad-sad-sad-site",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: {},
    published_deploy: null,
    screenshot_url: null,
    site_id: "b330d6ff-1374-45fa-9dc9-2287a09ac461",
    ssl: false,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://sad-sad-sad-site.netlify.app",
    state: "current",
    updated_at: "2019-12-10T21:52:54.762Z",
    url: "http://sad-sad-sad-site.netlify.app",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/sad-sad-site",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {},
    claimed: true,
    created_at: "2019-12-10T21:50:26.443Z",
    custom_domain: null,
    deploy_hook: null,
    deploy_id: "",
    deploy_url: "http://5f31efd0da650ecf809d284f--sad-sad-site.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: null,
    functions_config: {},
    functions_region: null,
    id: "4678efeb-9171-4c25-bf75-a24936ecb6d0",
    id_domain: "4678efeb-9171-4c25-bf75-a24936ecb6d0.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "sad-sad-site",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: {},
    published_deploy: null,
    screenshot_url: null,
    site_id: "4678efeb-9171-4c25-bf75-a24936ecb6d0",
    ssl: false,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://sad-sad-site.netlify.app",
    state: "current",
    updated_at: "2019-12-10T21:50:26.443Z",
    url: "http://sad-sad-site.netlify.app",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/sad-site",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {},
    claimed: true,
    created_at: "2019-12-10T21:47:36.082Z",
    custom_domain: null,
    deploy_hook: null,
    deploy_id: "",
    deploy_url: "http://5f31efd0da650ecf809d2850--sad-site.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: null,
    functions_config: {},
    functions_region: null,
    id: "de8ec926-010e-4f4c-b816-5413228cd0a2",
    id_domain: "de8ec926-010e-4f4c-b816-5413228cd0a2.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "sad-site",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: {},
    published_deploy: null,
    screenshot_url: null,
    site_id: "de8ec926-010e-4f4c-b816-5413228cd0a2",
    ssl: false,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://sad-site.netlify.app",
    state: "current",
    updated_at: "2019-12-10T21:47:36.082Z",
    url: "http://sad-site.netlify.app",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/very-happy-site",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {},
    claimed: true,
    created_at: "2019-12-10T21:45:23.487Z",
    custom_domain: null,
    deploy_hook: null,
    deploy_id: "",
    deploy_url: "http://5f31efd0da650ecf809d2851--very-happy-site.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: null,
    functions_config: {},
    functions_region: null,
    id: "6ee4a9c8-be23-4eb6-a4b3-7178e9fa5657",
    id_domain: "6ee4a9c8-be23-4eb6-a4b3-7178e9fa5657.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "very-happy-site",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: {},
    published_deploy: null,
    screenshot_url: null,
    site_id: "6ee4a9c8-be23-4eb6-a4b3-7178e9fa5657",
    ssl: false,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://very-happy-site.netlify.app",
    state: "current",
    updated_at: "2019-12-10T21:45:23.487Z",
    url: "http://very-happy-site.netlify.app",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    account_name: "Aldo Bucchi's team",
    account_slug: "aldonline",
    account_type: "Starter",
    admin_url: "https://app.netlify.com/sites/pensive-brattain-4728e8",
    analytics_instance_id: null,
    automatic_tls_provisioning: null,
    automatic_tls_provisioning_expired: false,
    build_id: "",
    build_image: "xenial",
    build_settings: {},
    capabilities: {},
    claimed: true,
    created_at: "2019-08-23T21:54:40.711Z",
    custom_domain: null,
    deploy_hook: null,
    deploy_id: "5d6060a02a5dba899966ee4b",
    deploy_url:
      "http://5d6060a02a5dba899966ee4b--pensive-brattain-4728e8.netlify.app",
    disabled: null,
    dns_zone_id: null,
    domain_aliases: [],
    error_message: null,
    force_ssl: null,
    functions_config: {},
    functions_region: null,
    id: "5d5665f7-fbdf-46db-9ff8-4aeea93aace2",
    id_domain: "5d5665f7-fbdf-46db-9ff8-4aeea93aace2.netlify.app",
    identity_instance_id: null,
    jwt_roles_path: "app_metadata.authorization.roles",
    jwt_secret: null,
    lifecycle_state: "active",
    managed_dns: true,
    max_domain_aliases: 100,
    name: "pensive-brattain-4728e8",
    notification_email: null,
    paid_individual_site_subscription: false,
    parent_user_id: null,
    password: null,
    plan: "nf_team_dev",
    plugins: [],
    premium: false,
    prerender: null,
    prerender_headers: null,
    processing_settings: {},
    published_deploy: {},
    screenshot_url:
      "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5d6060a02a5dba899966ee4b/screenshot.png",
    site_id: "5d5665f7-fbdf-46db-9ff8-4aeea93aace2",
    ssl: false,
    ssl_plan: null,
    ssl_status: null,
    ssl_url: "https://pensive-brattain-4728e8.netlify.app",
    state: "current",
    updated_at: "2019-08-23T21:54:44.174Z",
    url: "http://pensive-brattain-4728e8.netlify.app",
    use_functions: null,
    use_lm: null,
    user_id: "5ca4dcd877614601753fdded",
  },
]

export type R_getSite = typeof getSite
export const getSite = {
  id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
  site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
  plan: "nf_team_dev",
  ssl_plan: null,
  premium: false,
  claimed: true,
  name: "xenodochial-torvalds-5752f5",
  custom_domain: null,
  domain_aliases: [],
  password: null,
  notification_email: null,
  url: "http://xenodochial-torvalds-5752f5.netlify.app",
  admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
  deploy_id: "5f35b1befa10e1009b644d8e",
  build_id: "",
  deploy_url:
    "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
  state: "current",
  screenshot_url:
    "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5f35b1befa10e1009b644d8e/screenshot.png",
  created_at: "2020-08-13T21:33:50.944Z",
  updated_at: "2020-08-13T21:35:21.166Z",
  user_id: "5ca4dcd877614601753fdded",
  error_message: null,
  ssl: false,
  ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
  force_ssl: null,
  ssl_status: null,
  max_domain_aliases: 100,
  build_settings: {
    cmd: "gatsby build",
    dir: "public/",
    env: {},
    created_at: "2020-08-13T21:33:50.966Z",
    updated_at: "2020-08-13T21:33:50.966Z",
    private_logs: null,
    allowed_branches: ["master"],
    functions_dir: null,
    installation_id: 11237437,
    skip_prs: null,
    untrusted_flow: "review",
    base_rel_dir: true,
    stop_builds: false,
    public_repo: false,
    provider: "github",
    repo_type: "git",
    repo_url: "https://github.com/decoupled/netlify-test-site",
    repo_branch: "master",
    repo_path: "decoupled/netlify-test-site",
    base: null,
    deploy_key_id: null,
  },
  processing_settings: {
    css: { bundle: true, minify: true },
    js: { bundle: true, minify: true },
    images: { optimize: true },
    html: { pretty_urls: true },
    skip: true,
  },
  prerender: null,
  prerender_headers: null,
  deploy_hook: "https://api.netlify.com/hooks/github",
  published_deploy: {
    id: "5f35b1befa10e1009b644d8e",
    site_id: "f0acc552-da82-4a61-a0d4-2843fcd94695",
    build_id: "5f35b1befa10e1009b644d8c",
    state: "ready",
    name: "xenodochial-torvalds-5752f5",
    url: "http://xenodochial-torvalds-5752f5.netlify.app",
    ssl_url: "https://xenodochial-torvalds-5752f5.netlify.app",
    admin_url: "https://app.netlify.com/sites/xenodochial-torvalds-5752f5",
    deploy_url:
      "http://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
    deploy_ssl_url:
      "https://5f35b1befa10e1009b644d8e--xenodochial-torvalds-5752f5.netlify.app",
    created_at: "2020-08-13T21:33:50.988Z",
    updated_at: "2020-08-13T21:35:21.151Z",
    user_id: "5ca4dcd877614601753fdded",
    error_message: null,
    required: [],
    required_functions: [],
    commit_ref: null,
    review_id: null,
    branch: "master",
    commit_url: null,
    skipped: null,
    locked: null,
    log_access_attributes: {
      type: "firebase",
      url:
        "https://netlify-builds3.firebaseio.com/builds/5f35b1befa10e1009b644d8c/log",
      endpoint: "https://netlify-builds3.firebaseio.com",
      path: "/builds/5f35b1befa10e1009b644d8c/log",
      token:
        "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJpYXQiOjE1OTczNTkzNDYsImQiOnsidWlkIjoiIn19.pyn-gbe0lnOM8Mz05QE9K_Qr14rHwayIp8CXeNzozeo",
    },
    title: null,
    review_url: null,
    published_at: "2020-08-13T21:35:18.869Z",
    context: "production",
    deploy_time: 66,
    available_functions: [],
    summary: {
      status: "ready",
      messages: [
        {
          type: "info",
          title: "All files already uploaded",
          description:
            "All files already uploaded by a previous deploy with the same commits.",
          details: null,
        },
        {
          type: "info",
          title: "No redirect rules processed",
          description:
            "This deploy did not include any redirect rules. [Learn more about redirects](https://www.netlify.com/docs/redirects/).",
          details: "",
        },
        {
          type: "info",
          title: "No header rules processed",
          description:
            "This deploy did not include any header rules. [Learn more about headers](https://www.netlify.com/docs/headers-and-basic-auth/).",
          details: "",
        },
        {
          type: "info",
          title: "All linked resources are secure",
          description:
            "Congratulations! No insecure mixed content found in your files.",
          details: null,
        },
      ],
    },
    screenshot_url:
      "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5f35b1befa10e1009b644d8e/screenshot.png",
    site_capabilities: {
      title: "Netlify Team Free",
      asset_acceleration: true,
      form_processing: true,
      cdn_propagation: "partial",
      build_gc_exchange: "buildbot-gc",
      build_node_pool: "buildbot-external-ssd",
      domain_aliases: true,
      secure_site: false,
      prerendering: true,
      proxying: true,
      ssl: "custom",
      rate_cents: 0,
      yearly_rate_cents: 0,
      ipv6_domain: "cdn.makerloop.com",
      branch_deploy: true,
      managed_dns: true,
      geo_ip: true,
      split_testing: true,
      id: "nf_team_dev",
      cdn_tier: "reg",
    },
    committer: null,
    skipped_log: null,
    manual_deploy: false,
    file_tracking_optimization: true,
    plugin_state: "none",
  },
  managed_dns: true,
  jwt_secret: null,
  jwt_roles_path: "app_metadata.authorization.roles",
  account_slug: "aldonline",
  account_name: "Aldo Bucchi's team",
  account_type: "Starter",
  capabilities: {
    title: "Netlify Team Free",
    asset_acceleration: true,
    form_processing: true,
    cdn_propagation: "partial",
    build_gc_exchange: "buildbot-gc",
    build_node_pool: "buildbot-external-ssd",
    domain_aliases: true,
    secure_site: false,
    prerendering: true,
    proxying: true,
    ssl: "custom",
    rate_cents: 0,
    yearly_rate_cents: 0,
    ipv6_domain: "cdn.makerloop.com",
    branch_deploy: true,
    managed_dns: true,
    geo_ip: true,
    split_testing: true,
    id: "nf_team_dev",
    cdn_tier: "reg",
  },
  paid_individual_site_subscription: false,
  dns_zone_id: null,
  identity_instance_id: null,
  use_functions: null,
  parent_user_id: null,
  automatic_tls_provisioning: null,
  disabled: null,
  lifecycle_state: "active",
  id_domain: "f0acc552-da82-4a61-a0d4-2843fcd94695.netlify.app",
  use_lm: null,
  build_image: "xenial",
  automatic_tls_provisioning_expired: false,
  analytics_instance_id: null,
  functions_region: null,
  functions_config: { site_created_at: "2020-08-13T21:33:50.944Z" },
  plugins: [],
}

export type R_listPaymentMethodsForUser = typeof listPaymentMethodsForUser
export const listPaymentMethodsForUser = [
  {
    id: "5f2e2570848de092e7493930",
    method_name: "",
    type: "card",
    data: { card_type: "Visa", name: "Aldo Bucchi", last4: "5200" },
    state: "success",
    created_at: "2020-08-08T04:09:20.320Z",
    updated_at: "2020-08-08T04:09:20.320Z",
    account_id: "5ca4dcd877614601753fddee",
    customer_id: "5d2e4e3d4a7d2400093af2d6",
    zuora_id: "2c92a0ff73c76e2a0173cc423d3d3c73",
  },
]

export type R_listSiteDeploys = typeof listSiteDeploys
export const listSiteDeploys = [
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "production",
    created_at: "2020-01-14T08:25:33.998Z",
    deploy_ssl_url:
      "https://5e1d7afdb1161e930e1ed593--decoupled-dev.netlify.app",
    deploy_time: 4,
    deploy_url: "http://5e1d7afdb1161e930e1ed593--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1d7afdb1161e930e1ed593",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: "2020-01-14T08:25:38.340Z",
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-14T09:16:08.481Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "production",
    created_at: "2020-01-14T01:32:37.338Z",
    deploy_ssl_url:
      "https://5e1d1a35697bd8a5e4b215f9--decoupled-dev.netlify.app",
    deploy_time: 0,
    deploy_url: "http://5e1d1a35697bd8a5e4b215f9--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1d1a35697bd8a5e4b215f9",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: "2020-01-14T01:32:37.951Z",
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-14T08:25:38.346Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "deploy-preview",
    created_at: "2020-01-14T01:29:28.838Z",
    deploy_ssl_url:
      "https://5e1d1978dbbf015e10352078--decoupled-dev.netlify.app",
    deploy_time: 16,
    deploy_url: "http://5e1d1978dbbf015e10352078--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1d1978dbbf015e10352078",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: null,
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-14T01:29:45.385Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "production",
    created_at: "2020-01-14T00:23:49.973Z",
    deploy_ssl_url:
      "https://5e1d0a15dbbf0183ee35207c--decoupled-dev.netlify.app",
    deploy_time: 0,
    deploy_url: "http://5e1d0a15dbbf0183ee35207c--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1d0a15dbbf0183ee35207c",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: "2020-01-14T00:23:50.710Z",
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-14T01:32:37.956Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "deploy-preview",
    created_at: "2020-01-14T00:22:38.622Z",
    deploy_ssl_url:
      "https://5e1d09ce113a8e6860706510--decoupled-dev.netlify.app",
    deploy_time: 4,
    deploy_url: "http://5e1d09ce113a8e6860706510--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1d09ce113a8e6860706510",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: null,
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-14T00:22:42.737Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "production",
    created_at: "2020-01-13T21:49:18.855Z",
    deploy_ssl_url:
      "https://5e1ce5de41b538aa38831754--decoupled-dev.netlify.app",
    deploy_time: 5,
    deploy_url: "http://5e1ce5de41b538aa38831754--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1ce5de41b538aa38831754",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: "2020-01-13T21:49:24.038Z",
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-14T00:23:50.716Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "production",
    created_at: "2020-01-13T18:36:46.216Z",
    deploy_ssl_url:
      "https://5e1cb8be695b4501bbbf7009--decoupled-dev.netlify.app",
    deploy_time: 1,
    deploy_url: "http://5e1cb8be695b4501bbbf7009--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1cb8be695b4501bbbf7009",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: "2020-01-13T18:36:47.444Z",
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-13T21:49:24.047Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "deploy-preview",
    created_at: "2020-01-13T18:36:18.577Z",
    deploy_ssl_url:
      "https://5e1cb8a2695b4501a4bf700c--decoupled-dev.netlify.app",
    deploy_time: 1,
    deploy_url: "http://5e1cb8a2695b4501a4bf700c--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1cb8a2695b4501a4bf700c",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: null,
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-13T18:36:19.999Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "deploy-preview",
    created_at: "2020-01-13T10:37:16.713Z",
    deploy_ssl_url:
      "https://5e1c485c1d9a92c47dd4a6ab--decoupled-dev.netlify.app",
    deploy_time: 5,
    deploy_url: "http://5e1c485c1d9a92c47dd4a6ab--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1c485c1d9a92c47dd4a6ab",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: null,
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-13T10:37:21.753Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
  {
    admin_url: "https://app.netlify.com/sites/decoupled-dev",
    available_functions: [],
    branch: null,
    build_id: null,
    commit_ref: null,
    commit_url: null,
    committer: null,
    context: "deploy-preview",
    created_at: "2020-01-13T07:25:24.262Z",
    deploy_ssl_url:
      "https://5e1c1b64ae97a760d48d1fc8--decoupled-dev.netlify.app",
    deploy_time: 10,
    deploy_url: "http://5e1c1b64ae97a760d48d1fc8--decoupled-dev.netlify.app",
    error_message: null,
    file_tracking_optimization: false,
    id: "5e1c1b64ae97a760d48d1fc8",
    locked: null,
    log_access_attributes: {},
    manual_deploy: true,
    name: "decoupled-dev",
    plugin_state: "none",
    published_at: null,
    required: [],
    required_functions: [],
    review_id: null,
    review_url: null,
    screenshot_url: null,
    site_capabilities: {},
    site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
    skipped: null,
    skipped_log: null,
    ssl_url: "https://dev.decoupled.com",
    state: "ready",
    summary: {},
    title: null,
    updated_at: "2020-01-13T07:25:34.490Z",
    url: "https://dev.decoupled.com",
    user_id: "5ca4dcd877614601753fdded",
  },
]

export type SiteDeployRaw = typeof siteDeployExample

const siteDeployExample = {
  id: "5e55bfaa1036fdb7aa9759ab",
  site_id: "fb6e1e92-99a6-4684-bdf2-e5f0397119ae",
  build_id: null,
  state: "ready",
  name: "decoupled-dev",
  url: "https://dev.decoupled.com",
  ssl_url: "https://dev.decoupled.com",
  admin_url: "https://app.netlify.com/sites/decoupled-dev",
  deploy_url: "http://5e55bfaa1036fdb7aa9759ab--decoupled-dev.netlify.app",
  deploy_ssl_url: "https://5e55bfaa1036fdb7aa9759ab--decoupled-dev.netlify.app",
  created_at: "2020-02-26T00:45:30.387Z",
  updated_at: "2020-08-09T09:00:51.864Z",
  user_id: "5ca4dcd877614601753fdded",
  error_message: null,
  required: [],
  required_functions: [],
  commit_ref: null,
  review_id: null,
  branch: null,
  commit_url: null,
  skipped: null,
  locked: null,
  log_access_attributes: {
    type: "firebase",
    url:
      "https://netlify-builds1.firebaseio.com/deploys/5e55bfaa1036fdb7aa9759ab/log",
    endpoint: "https://netlify-builds1.firebaseio.com",
    path: "/deploys/5e55bfaa1036fdb7aa9759ab/log",
    token:
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJpYXQiOjE1OTczMDE4NDQsImQiOnsidWlkIjoiIn19.WhJnAVuOoKcHiAYsA1qCPHxuKLYxQhnjy_QFSDZgLrc",
  },
  title: null,
  review_url: null,
  published_at: "2020-02-26T00:45:36.205Z",
  context: "production",
  deploy_time: 5,
  available_functions: [],
  summary: {
    status: "ready",
    messages: [
      {
        type: "info",
        title: "5 new files uploaded",
        description: "1 generated page and 4 assets changed.",
        details: "New pages include:\n- index.html\n",
      },
      {
        type: "info",
        title: "1 redirect rule processed",
        description: "All redirect rules deployed without errors.",
        details: "",
      },
      {
        type: "info",
        title: "No header rules processed",
        description:
          "This deploy did not include any header rules. [Learn more about headers](https://www.netlify.com/docs/headers-and-basic-auth/).",
        details: "",
      },
      {
        type: "info",
        title: "All linked resources are secure",
        description:
          "Congratulations! No insecure mixed content found in your files.",
        details: null,
      },
    ],
  },
  screenshot_url:
    "https://353a23c500dde3b2ad58-c49fe7e7355d384845270f4a7a0a7aa1.ssl.cf2.rackcdn.com/5e55bfaa1036fdb7aa9759ab/screenshot.png",
  site_capabilities: {
    title: "Netlify Team Free",
    asset_acceleration: true,
    form_processing: true,
    cdn_propagation: "partial",
    build_gc_exchange: "buildbot-gc",
    build_node_pool: "buildbot-external-ssd",
    domain_aliases: true,
    secure_site: false,
    prerendering: true,
    proxying: true,
    ssl: "custom",
    rate_cents: 0,
    yearly_rate_cents: 0,
    ipv6_domain: "cdn.makerloop.com",
    branch_deploy: true,
    managed_dns: true,
    geo_ip: true,
    split_testing: true,
    id: "nf_team_dev",
    cdn_tier: "reg",
  },
  committer: null,
  skipped_log: null,
  manual_deploy: true,
  file_tracking_optimization: false,
  plugin_state: "none",
}
export type R_getCurrentUser = typeof getCurrentUser
export const getCurrentUser = {
  id: "5ca4dcd877614601753fdded",
  uid: null,
  full_name: "Aldo Bucchi",
  avatar_url: "https://avatars2.githubusercontent.com/u/154884?v=4",
  email: "aldo.bucchi@gmail.com",
  affiliate_id: "",
  site_count: 10,
  created_at: "2019-04-03T16:18:32.151Z",
  last_login: "2020-06-08T20:39:01.247Z",
  login_providers: ["github"],
  onboarding_progress: {
    slides: "closed",
    notifications_read_at: "2020-07-21T13:00:00Z",
  },
  slug: "aldonline",
  sandbox: false,
  connected_accounts: { github: "aldonline" },
  pending_email: null,
  has_pending_email_verification: false,
  mfa_enabled: false,
  saml_account_id: "",
  tracking_id: "5ca4dcd877614601753fdded",
}
